/**
 * Data sample for tbl.js
 * Input expected in jsGrid Class
 *
 new jsgrid(
        domElement,
        { 'rows': dataset.rows, 'headers': headers }, options);
 */

const headers = [
    { name: 'project_id', title: 'ID', 'style': { display: 'none' } },
    { name: 'parent_id', title: 'PID', 'style': { display: 'none' } },
    { name: 'project_name', title: 'Project', 'style': { width: '15%' } },
    { name: 'description', title: 'Description', 'style': { width: '15%' } },
    { name: 'start_date', title: 'Started', 'style': { width: '7%' } },
    { name: 'end_date', title: 'To end', 'style': { width: '7%' } },
    { name: 'target_budget', title: 'Budget', 'style': { width: '180px' } },
    { name: 'actual_budget', title: 'Forecast', 'style': { width: '150px' } }
];


let dataset = {
    "total": 21,
    "fields": [
        "project_id",
        "parent_id",
        "creator_id",
        "project_name",
        "alias",
        "description",
        "start_date",
        "end_date",
        "status",
        "color_hex_code",
        "target_budget",
        "actual_budget",
        "priority",
        "type",
        "internal"
    ],
    "rows": [
        {
            "project_id": "1",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto 1",
            "alias": "uno",
            "description": "Primer proyecto de la primera ola",
            "start_date": "2013-12-08 15:01:20",
            "end_date": "2013-12-18 15:01:20",
            "status": "1",
            "color_hex_code": "EFdd77",
            "target_budget": "345.00",
            "actual_budget": "244.23",
            "priority": "45",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "2",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto 2",
            "alias": "dos",
            "description": "Segundo proyecto de la primera ola",
            "start_date": "2013-10-24 11:19:47",
            "end_date": "2013-10-31 11:19:47",
            "status": "1",
            "color_hex_code": "EFD777",
            "target_budget": "5644.00",
            "actual_budget": "237.19",
            "priority": "100",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "3",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "tres",
            "alias": "tres",
            "description": "Tercer proyecto",
            "start_date": "2013-04-11 04:54:37",
            "end_date": "2013-04-17 04:54:37",
            "status": "1",
            "color_hex_code": "FFDD33",
            "target_budget": "3434.00",
            "actual_budget": "248.68",
            "priority": "65",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "4",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto cuatro",
            "alias": "dos",
            "description": "proyecto teste 4",
            "start_date": "2013-11-04 07:53:25",
            "end_date": "2013-11-13 07:53:25",
            "status": "1",
            "color_hex_code": "DFFF33",
            "target_budget": "2343.00",
            "actual_budget": "237.20",
            "priority": "76",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "5",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto cinco",
            "alias": "dos",
            "description": "quinto project 5",
            "start_date": "2013-06-26 18:02:53",
            "end_date": "2013-07-22 18:02:53",
            "status": "1",
            "color_hex_code": "CF4466",
            "target_budget": "65445.00",
            "actual_budget": "235.36",
            "priority": "87",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "6",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto seis",
            "alias": "dos",
            "description": "proyecto seis de prueba",
            "start_date": "2013-11-03 11:53:48",
            "end_date": "2013-11-19 11:53:48",
            "status": "1",
            "color_hex_code": "EF4433",
            "target_budget": "5434.00",
            "actual_budget": "260.59",
            "priority": "94",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "7",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto siete",
            "alias": "dos",
            "description": "projecto 7 de prueba",
            "start_date": "2013-10-21 22:40:04",
            "end_date": "2013-10-24 22:40:04",
            "status": "1",
            "color_hex_code": "FFDDCC",
            "target_budget": "6523.00",
            "actual_budget": "242.30",
            "priority": "34",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "8",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto ocho",
            "alias": "dos",
            "description": "la paredes azules",
            "start_date": "2013-07-12 22:58:35",
            "end_date": "2013-08-07 22:58:35",
            "status": "1",
            "color_hex_code": "CCFFDD",
            "target_budget": "4352.00",
            "actual_budget": "255.10",
            "priority": "33",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "9",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto nueve",
            "alias": "dos",
            "description": "pajarito azul de proyecto novo",
            "start_date": "2013-03-18 16:12:23",
            "end_date": "2013-03-18 16:12:23",
            "status": "1",
            "color_hex_code": "EFDC55",
            "target_budget": "7654.00",
            "actual_budget": "253.99",
            "priority": "23",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "10",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto diez",
            "alias": "dos",
            "description": "decimo proyecto de prueba azul y amarillo",
            "start_date": "2013-05-30 05:25:50",
            "end_date": "2013-06-13 05:25:50",
            "status": "1",
            "color_hex_code": "FFDC77",
            "target_budget": "7687.00",
            "actual_budget": "240.08",
            "priority": "2",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "11",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto deciuno",
            "alias": "dos",
            "description": "eleventh project",
            "start_date": "2013-06-08 19:51:40",
            "end_date": "2013-06-20 19:51:40",
            "status": "1",
            "color_hex_code": "6FD777",
            "target_budget": "6576.00",
            "actual_budget": "263.82",
            "priority": "2",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "12",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto decidos",
            "alias": "dos",
            "description": "proyecto de prueba sin tareas",
            "start_date": "2013-12-07 04:20:32",
            "end_date": "2013-12-26 04:20:32",
            "status": "1",
            "color_hex_code": "EFD7FF",
            "target_budget": "6758.00",
            "actual_budget": "244.25",
            "priority": "33",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "13",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto catorce",
            "alias": "dos",
            "description": "tarea sin proyecto de prueba y pruebas sin tareas",
            "start_date": "2013-06-15 03:27:19",
            "end_date": "2013-07-12 03:27:19",
            "status": "1",
            "color_hex_code": "55D777",
            "target_budget": "6584.00",
            "actual_budget": "255.21",
            "priority": "22",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "14",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto quince",
            "alias": "dos",
            "description": "Loren ipsum dolor mas dolor",
            "start_date": "2013-05-30 21:34:37",
            "end_date": "2013-06-19 21:34:37",
            "status": "1",
            "color_hex_code": "44D777",
            "target_budget": "8767.00",
            "actual_budget": "248.68",
            "priority": "12",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "15",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto dicesies",
            "alias": "dos",
            "description": "Proyecto de 15 otros",
            "start_date": "2013-09-05 18:50:50",
            "end_date": "2013-09-22 18:50:50",
            "status": "1",
            "color_hex_code": "33D777",
            "target_budget": "6556.00",
            "actual_budget": "243.19",
            "priority": "21",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "16",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto diecisupre",
            "alias": "dos",
            "description": "Preparacion de alimentos",
            "start_date": "2013-03-22 22:49:59",
            "end_date": "2013-04-20 22:49:59",
            "status": "1",
            "color_hex_code": "22D777",
            "target_budget": "3443.00",
            "actual_budget": "235.30",
            "priority": "12",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "17",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto decisiete",
            "alias": "dos",
            "description": "Elaboración de pancartas y afiches",
            "start_date": "2013-12-24 02:57:05",
            "end_date": "2013-12-26 02:57:05",
            "status": "1",
            "color_hex_code": "11D777",
            "target_budget": "3423.00",
            "actual_budget": "242.32",
            "priority": "32",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "18",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto 18",
            "alias": "dos",
            "description": "Proyecto de prueba para probar la lista",
            "start_date": "2013-05-13 11:35:08",
            "end_date": "2013-05-27 11:35:08",
            "status": "1",
            "color_hex_code": "111111",
            "target_budget": "3454.00",
            "actual_budget": "241.10",
            "priority": "43",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "19",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto 19",
            "alias": "dos",
            "description": "Preparacion de libro anual sobre relleno",
            "start_date": "2013-10-14 18:24:04",
            "end_date": "2013-10-19 18:24:04",
            "status": "1",
            "color_hex_code": "EFD711",
            "target_budget": "3454.00",
            "actual_budget": "243.96",
            "priority": "33",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "20",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto 20",
            "alias": "dos",
            "description": "Preparación de primera fila",
            "start_date": "2013-11-25 02:34:36",
            "end_date": "2013-12-07 02:34:36",
            "status": "1",
            "color_hex_code": "EFD755",
            "target_budget": "5534.00",
            "actual_budget": "261.88",
            "priority": "44",
            "type": "9",
            "internal": "1"
        },
        {
            "project_id": "21",
            "parent_id": "0",
            "creator_id": "1",
            "project_name": "Proyecto 21",
            "alias": "dos",
            "description": "Investigación de piedras encontradas en marte",
            "start_date": "2013-03-13 23:00:29",
            "end_date": "2013-03-28 23:00:29",
            "status": "1",
            "color_hex_code": "EFDD66",
            "target_budget": "5555.00",
            "actual_budget": "252.92",
            "priority": "25",
            "type": "9",
            "internal": "1"
        }
    ]
}


